Homework1
made-ml-in-prod-2021/sokoloid pull request #2
Opened 2021-05-08 12:16 UTC by SokoloiD

Программа и утилиты для определения класса территории по GPS координатам точки и изображению генплана города.
Тип территории определяется способом заливки области на генплане.
 Заливка может представлять собой как цвет, так и орнамент (штриховка,периодический рисунок, набор точек разных цветов).
 На заливку могут быть нанесены надписи черно-белым шрифтом и через заливку темным фоном проступают нанесенные на генплан 
 строения). Таким образом, при GPS координаты точки, для которой делается запрос, могут оказаться на месте надписи на карте, на границе областей из разных классов
 
 Для решения задачи разработан набор утилит:
 geo_map.py   -непосредственно классификация территории по gps коодинатам. 
 на вход поступает файл с координатами в  формате
 [55.86605046256052, 49.07751363142922]
[55.85844989210669, 49.097790215192205]
[55.86076205652522, 49.1011128167036]
[55.860484236577484, 49.09768561964577]
[55.856545533835046, 49.08306987914005]

на выходе файл с расшифровкой (координаты GPS, пиксели, класс)
[55.860484236577484, 49.09768561964577]	13887	7324	Зона перспективного формирования жилых районов, освоения территории при условии разработки проекта планировки и Зона многоквартиной многоэтажной жилой застройки с высокой долей общественных функций
[55.856545533835046, 49.08306987914005]	13196	7650	Зона индифидуальной и блокированной жилой застройки
[55.85318312116005, 49.082583088226954]	13179	7930	Зона многоквартиной многоэтажной жилой застройки
[55.86561202210543, 49.10175555946954]	14071	6897	Зона многоквартиной многоэтажной жилой застройки

train.py  -утилита для тренировки модели на основе resnet18. В качестве входных данных подается набор маршрутов, проходящих по территории одного класса.
Маршрут задается набором координат точек. Формат - csv
class	x1	y1	x2	y2	x3	y3	x4	y4	x5	y5	x6	y6	x7	y7	x8	y8	x9	y9	x10	y10
0	16227	13054	16300	13017	16286	12929	16117	12904	16105	13024										
0	15830	12909																		
1	19043	11043	18991	11038	19064	10836	19090	10836	19150	10962	19140	10990								

sort_images.py  утилита для проверки правильности классификации. На вход получат так же как и train.py файл с маршрутами. 
подсчитывает количество неправильных классификация и разбивкой по парам (target-predit) . Так же может в целях отладки сохранять изображение окрестностей точек, для которой проводилась классификация

библиотеки для работы
common_utils.py и train_utils.py

2021-05-08 20:44 UTC, nickdndev reviewed
Все отлично , но есть пару моментов с конфигами и размывания логики по файлам.
Жаль ,что нет тестов

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/common_utils.py
> +        """
необходимо добавить проверку , что fit был вызван  + pytest 
https://github.com/scikit-learn/scikit-learn/blob/15a949460/sklearn/preprocessing/_data.py#L432

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/conf/config.yaml
> +path_to_root: ../../../../..
стоит пересмотреть данный подход '../../../../..' слишком большая вложенность

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/conf/sort_images_config.yaml
> +path_to_root: ../../../../..
стоит пересмотреть данный подход '../../../../..' слишком большая вложенность

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/conf/train_config.yaml
> +path_to_root: ..\..\..\..\..
стоит пересмотреть данный подход '../../../../..' слишком большая вложенность

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/conf/train_config2.yaml
> +path_to_root: ..\..\..\..\..
стоит пересмотреть данный подход '../../../../..' слишком большая вложенность

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/geo_map.py
> +        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
надо перенести в дефолные параметры и потом через конфиг прокидывать

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ("image",)),
надо перенести в дефолные параметры и потом через конфиг прокидывать

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/train.py
> +        TransformByKeys(transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ("image",)),
надо перенести в дефолные параметры и потом через конфиг прокидывать

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/train.py
> +        TransformByKeys(transforms.RandomHorizontalFlip(), ("image",)),
стоит сгруппировать трансформеры в одном месте, чтобы можно было все в одном месте редактировать , покрывать тестами и так далее, а не размазывать по всем файлам

2021-05-08 20:44 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(RandomizeCoords(deviation=cfg.deviation), ("coord",)),
стоит сгруппировать трансформеры в одном месте, чтобы можно было все в одном месте редактировать , покрывать тестами и так далее, а не размазывать по всем файлам

2021-05-08 21:45 UTC, nickdndev requested changes

2021-05-08 21:45 UTC, nickdndev commented on ml_project/src/model/geo_map.py
> +    map_image: str = MISSING
стоит вынести в отдельный модуль

2021-05-08 21:45 UTC, nickdndev commented on ml_project/src/model/geo_map.py
> +class Config(DictConfig):
стоит вынести в отдельный модуль

2021-05-08 21:45 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +    coord: tuple = (0, 0)
стоит вынести в отдельный модуль

2021-05-08 21:45 UTC, nickdndev commented on ml_project/src/model/train_utils.py
> +    classifier = nn.Sequential(nn.Linear(model.fc.in_features, 512),
Кофигурацию модели  стоит вынести в конфиг

2021-05-08 21:45 UTC, nickdndev commented on ml_project/src/model/train_utils.py
> +
в utils выносят куски кода, которые используют в проекте ,чтобы не было дублирвоания.

Но в данном случ. стоит разделить на dataset.py, train_validate.py и так делее т.к. это не utils

2021-05-09 20:55 UTC, SokoloiD commented on ml_project/src/model/common_utils.py
> +        """
В файле test_utils.py эта проверка делается. (только эта)

2021-05-09 20:56 UTC, SokoloiD commented on ml_project/src/model/conf/config.yaml
> +path_to_root: ../../../../..
ок. согласен. не красиво. переделаю

2021-05-09 20:56 UTC, SokoloiD commented on ml_project/src/model/conf/sort_images_config.yaml
> +path_to_root: ../../../../..
ок

2021-05-09 20:56 UTC, SokoloiD commented on ml_project/src/model/conf/train_config.yaml
> +path_to_root: ..\..\..\..\..
ок

2021-05-09 20:56 UTC, SokoloiD commented on ml_project/src/model/geo_map.py
> +        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
ок

2021-05-09 20:56 UTC, SokoloiD commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ("image",)),
ок

2021-05-09 20:57 UTC, SokoloiD commented on ml_project/src/model/train.py
> +        TransformByKeys(transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ("image",)),
ок

2021-05-09 20:57 UTC, SokoloiD commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(RandomizeCoords(deviation=cfg.deviation), ("coord",)),
согласен. в отдельный файл вынести ?

2021-05-09 20:58 UTC, SokoloiD commented on ml_project/src/model/geo_map.py
> +class Config(DictConfig):
не понял. отдельный модуль для класса конфигураций ?

2021-05-09 20:59 UTC, SokoloiD commented on ml_project/src/model/sort_images.py
> +    coord: tuple = (0, 0)
не понятно зачем. класс маленький. применяется только в одном файле. сделан для удобства работы с данными. На мой взгляд удобнее его держать там, где он непосредственно используется

2021-05-09 21:02 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(RandomizeCoords(deviation=cfg.deviation), ("coord",)),
Да ,все верно, когда эти классы сгруппированы отдельно ,то код с основной логикой легче читается

2021-05-09 21:04 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +        TransformByKeys(RandomizeCoords(deviation=cfg.deviation), ("coord",)),
Да ,все верно

2021-05-09 21:05 UTC, SokoloiD commented on ml_project/src/model/train_utils.py
> +    classifier = nn.Sequential(nn.Linear(model.fc.in_features, 512),
тут мне  не очевидно. с одной стороны 512 меджик намбер, с другой - это не гиперпараметр модели. может оформить его по другому , но оставить в конфигурацию в теле процедуры

2021-05-09 21:07 UTC, SokoloiD commented on ml_project/src/model/train_utils.py
> +
ок.
как вариант модули 
conf_classes.py
data_set.py для датасетов и даталоадеров
transformers.py для трансформеров

2021-05-09 21:13 UTC, nickdndev commented on ml_project/src/model/sort_images.py
> +    coord: tuple = (0, 0)
Согласен ,сейчас возникает вопрос зачем, но на проектах дата классы выносят отдельно ,чтобы разделить проект на структурные слои .

Обычно слои бывают такие :
Dto (data trasport object )/ data class 
Services 
Utils 
Configs 
И так далее 
Чтобы новый разработчик сразу мог по структуре проекта быстро сориентироваться  + это даёт возможность масштабировать проект

Это из моего опыта и оно может идти в разрез с преподавателем и требованиями к этой дз.
Поэтому этот комментарий опционален

2021-05-09 21:16 UTC, nickdndev commented on ml_project/src/model/geo_map.py
> +class Config(DictConfig):
Да ,все верно ,в отдельных модель для конфигоа

2021-05-23 14:18 UTC, Sergey-Pravdyukov commented
Проведи пожалуйста самооценку.

2021-05-23 15:02 UTC, Sergey-Pravdyukov requested changes
Проведи пожалуйста самооценку.

2021-05-24 05:25 UTC, SokoloiD commented
> Проведи пожалуйста самооценку.

Сергей, самооценка в readme.md. В след раз сделаю нагляднее
Назовите ветку homework1 (1 балл)

В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла)

Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов)
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)

Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов)

использованы логгеры (2 балла)

написаны тесты на отдельные модули и на прогон всего пайплайна(0/3 баллов)

Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов)

можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
можно просто руками посоздавать данных, собственноручно написанными функциями (файл /queries/small_query.csv скачать по ссылке выше)
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается)
Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)

Используются датаклассы для сущностей из конфига, а не голые dict (3 балла)

Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) Трансформеры (GpsToPixelTransformer,и др)

Обучите модель (train.py), запишите в readme как это предлагается (3 балла)

напишите функцию predict (geo_map.py), которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)

Используется hydra (https://hydra.cc/docs/intro/) (3 балла - доп баллы)

Настроен CI(прогон тестов, линтера) на основе github actions (0/3 балла - доп баллы

Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы)

Итог
1
2
2
1
2
2
0
3
3
3
3
3
3
3
0
1

Итог 32 балла

2021-06-09 20:03 UTC, merged

2021-06-11 10:52 UTC, Mikhail-M commented
Аппрува тут нет, мержить это было нельзя

2021-06-11 12:48 UTC, SokoloiD commented
Упс. Что теперь делать?  Я, к сожалению, с гитом только начинаю разбираться

2021-06-29 07:58 UTC, Sergey-Pravdyukov commented
32 балла.